# Generated by Django 6.0.6 on 2026-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('title', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
