# Generated by Django 6.0.6 on 2026-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_genre_platform_game_cover_url_game_igdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
