# Generated by Django 6.0.6 on 2026-07-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='itad_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='priceentry',
            unique_together={('game', 'store')},
        ),
    ]
