# Generated by Django 6.0.6 on 2026-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_itad_slug_game_steam_id_priceentry_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
